GP_MVC/Models/Year.cs
namespace GP_MVC.Models
{
    public class Year
    {
        public int Id { get; set; }
        public int Index { get; set; }
        public string Name { get; set; }
        public ICollection<Term> Terms { get; set; }
        public ICollection<ApplicationUserYear> ApplicationUserYears { get; set; }
    }
}

GP_MVC/Areas/Teacher/Controllers/YearController.cs
using GP_MVC.Models;
using GP_MVC.Utility;
using GP_MVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace GP_MVC.Areas.Teacher.Controllers
{
    [Authorize(Roles = StaticDetails.Teacher)]
    [Area(nameof(Teacher))]
    [Route(nameof(Teacher) + "/[controller]/[action]")]
    public class YearController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public YearController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {

            if (HttpContext.Session.GetString("created") != null)
            {
                ViewBag.created = true;
                HttpContext.Session.Remove("created");
            }
            if (HttpContext.Session.GetString("updated") != null)
            {
                ViewBag.updated = true;
                HttpContext.Session.Remove("updated");
            }
            if (HttpContext.Session.GetString("deleted") != null)
            {
                ViewBag.deleted = true;
                HttpContext.Session.Remove("deleted");
            }

            var Course = await _context.Years.Where(x => x.Index != 900000000).ToListAsync();

            return View(Course);
        }

        public async Task<IActionResult> TermIndex(int id)
        {

            if (HttpContext.Session.GetString("created") != null)
            {
                ViewBag.created = true;
                HttpContext.Session.Remove("created");
            }
            if (HttpContext.Session.GetString("updated") != null)
            {
                ViewBag.updated = true;
                HttpContext.Session.Remove("updated");
            }
            if (HttpContext.Session.GetString("deleted") != null)
            {
                ViewBag.deleted = true;
                HttpContext.Session.Remove("deleted");
            }

            var Course = await _context.Terms.Include(y => y.Year).Where(x => x.YearId == id).ToListAsync();
            ViewBag.YearId = id;
            return View(Course);
        }

        public async Task<IActionResult> MaterialIndex(int id)
        {

            if (HttpContext.Session.GetString("created") != null)
            {
                ViewBag.created = true;
                HttpContext.Session.Remove("created");
            }
            if (HttpContext.Session.GetString("updated") != null)
            {
                ViewBag.updated = true;
                HttpContext.Session.Remove("updated");
            }
            if (HttpContext.Session.GetString("deleted") != null)
            {
                ViewBag.deleted = true;
                HttpContext.Session.Remove("deleted");
            }

            string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var teacher = await _context.Users.FirstOrDefaultAsync(x => x.Id == userId);

            var Course = await _context.Materials.Include(y => y.Term).Where(x => x.TermId == id && x.Name == teacher.Subject).ToListAsync();
            ViewBag.TermId = id;
            return View(Course);
        }

        public async Task<IActionResult> ExamIndex(int id)
        {

            if (HttpContext.Session.GetString("created") != null)
            {
                ViewBag.created = true;
                HttpContext.Session.Remove("created");
            }
            if (HttpContext.Session.GetString("updated") != null)
            {
                ViewBag.updated = true;
                HttpContext.Session.Remove("updated");
            }
            if (HttpContext.Session.GetString("deleted") != null)
            {
                ViewBag.deleted = true;
                HttpContext.Session.Remove("deleted");
            }

            var Course = await _context.Exams.Include(y => y.Material).Where(x => x.MaterialId == id).ToListAsync();

            var users = await (from x in _context.Users
                               join userRole in _context.UserRoles
                               on x.Id equals userRole.UserId
                               join role in _context.Roles
                               on userRole.RoleId equals role.Id
                               where role.Name == StaticDetails.Teacher
                               select x)
                               .ToListAsync();

            ViewBag.Teachers = users;
            ViewBag.MaterialId = id;
            return View(Course);
        }

        [HttpGet]
        public async Task<IActionResult> AddExam(int id)
        {
            ViewBag.MaterialId = id;

            var users = await (from x in _context.Users
                               join userRole in _context.UserRoles
                               on x.Id equals userRole.UserId
                               join role in _context.Roles
                               on userRole.RoleId equals role.Id
                               where role.Name == StaticDetails.Teacher
                               select x)
                               .ToListAsync();

            ViewBag.Teachers = users;

            ViewBag.Materials = _context.Materials.ToList();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddExam(int id, ExamVM examDtos, string? returnUrl = null)
        {
            ViewBag.MaterialId = id;
            if (examDtos == null)
            {
                TempData["ErrorMessage"] = "Invalid exam data.";
                return RedirectToAction("AddExam");
            }

            var material = await _context.Materials.FindAsync(examDtos.MaterialId);

            string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var teacher = await _context.Users.FirstOrDefaultAsync(x => x.Id == userId);

            if (teacher == null || teacher.Subject != material.Name)
            {
                TempData["ErrorMessage"] = "You are not authorized to add grades for this material.";
                return RedirectToAction("AddExam");
            }

            if (_context.Exams.Any(e => e.Name == examDtos.Name && e.Material.Id == material.Id))
            {
                TempData["ErrorMessage"] = $"An exam with name '{examDtos.Name}' already exists for this material.";
                return RedirectToAction("AddExam");
            }

            var totalExamGradesInMaterial = _context.Exams.Where(e => e.Material.Id == material.Id).Sum(e => e.Exam_Grade);
            if (totalExamGradesInMaterial + examDtos.Exam_Grade > material.M_grade)
            {
                TempData["ErrorMessage"] = "Total exam grades exceed material grade.";
                return RedirectToAction("AddExam");
            }

            var exam = new Exam
            {
                Name = examDtos.Name,
                Exam_Grade = examDtos.Exam_Grade,
                Material = material
            };


             if (examDtos.Image != null)
            {
                string[] allowedExtensions = { ".png", ".jpg", ".jpeg" };
                if (!allowedExtensions.Contains(Path.GetExtension(examDtos.Image.FileName).ToLower()))
                {
                    TempData["ErrorMessage"] = "Only .png and .jpg and .jpeg images are allowed!";
                    return RedirectToAction("AddExam");
                }

                // Send image to API
                using (var httpClient = new HttpClient())
                {
                    using (var form = new MultipartFormDataContent())
                    {
                        using (var fileStream = examDtos.Image.OpenReadStream())
                        {
                            form.Add(new StreamContent(fileStream), "Image", examDtos.Image.FileName);

                            var response = await httpClient.PostAsync("http://ablexav1.runasp.net/api/Exam/AddExamImage", form);

                            if (response.IsSuccessStatusCode)
                            {
                                var uniqueFileName = await response.Content.ReadAsStringAsync();
                                exam.Image = uniqueFileName;
                            }
                            else
                            {
                                TempData["ErrorMessage"] = "Failed to upload image.";
                                return RedirectToAction("AddExam");
                            }
                        }
                    }
                }
            }

            _context.Exams.Add(exam);
            await _context.SaveChangesAsync();
            HttpContext.Session.SetString("created", "true");

            return RedirectToAction("ExamIndex", new { id = examDtos.MaterialId });
        }


        public async Task<IActionResult> EditExam(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exam = await _context.Exams.FindAsync(id);
            if (exam == null)
            {
                return NotFound();
            }

            ViewBag.MaterialId = exam.MaterialId;

            var editExamVM = new EditExamVM
            {
                Id = exam.Id,
                Name = exam.Name,
                Exam_Grade = exam.Exam_Grade,
                MaterialId = exam.MaterialId,
            };

            return View(editExamVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditExam(EditExamVM model)
        {
            try
            {
                var question = await _context.Exams.FirstOrDefaultAsync(s => s.Id == model.Id);

GP_MVC/Areas/Manager/Views/Year/AddMaterial.cshtml
@model GP_MVC.Models.Material
@{
    ViewData["Title"] = "Add Material";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}

<div class="br-pagetitle">
    <h3 class="text-info mr-3">Add Material</h3>
</div>

<div class="br-pagebody">
    <div class="br-section-wrapper">
        <div class="row">
            <div class="col-xl-12">
                <div class="form-layout form-layout-4">
                    <form method="post" asp-action="AddMaterial" asp-controller="Year" asp-route-returnurl="@ViewData["ReturnUrl"]">
                        <input type="hidden" asp-for="Id" />
                        <input type="hidden" asp-for="TermId" value="@ViewBag.TermId" />

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="row mb-3">
                            <label class="col-sm-4 form-control-label">Material Name: <span class="tx-danger">*</span></label>
                            <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                                <input asp-for="Name" type="text" class="form-control" placeholder="Material Name" required>
                                <span class="text-danger" asp-validation-for="Name"></span>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-sm-4 form-control-label">Material Grade: <span class="tx-danger">*</span></label>
                            <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                                <input asp-for="M_grade" type="number" class="form-control" placeholder="Material Grade" required>
                                <span class="text-danger" asp-validation-for="M_grade"></span>
                            </div>
                        </div>
                        
                        <div class="form-layout-footer mg-t-30 text-center">
                            <input type="submit" value="Save" class="btn btn-info">
                            <a asp-action="MaterialIndex" asp-controller="Year" asp-route-id="@ViewBag.TermId" class="btn btn-secondary">Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        $(document).ready(function () {
            var errorMessage = '@TempData["ErrorMessage"]';
            if (errorMessage) {
                alert(errorMessage);
            }
        });
    </script>
}

GP_MVC/Areas/Manager/Views/Year/Create.cshtml
@using GP_MVC.Models
@model Year
@{
    ViewData["Title"] = "Create Year";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}

<div class="br-pagetitle">
    <h3 class="text-info mr-3">Add New Year</h3>
</div><!-- d-flex -->

<div class="br-pagebody">
    <div class="br-section-wrapper">
        <div class="row">
            <div class="col-xl-12">
                <div class="form-layout form-layout-4">
                    <form method="post" asp-action="Create" asp-controller="Year" asp-route-returnurl="@ViewData["ReturnUrl"]">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="row mb-3">
                            <label class="col-sm-4 form-control-label">Year Name: <span class="tx-danger">*</span></label>
                            <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                                <input asp-for="Name" type="text" class="form-control" placeholder="Year Name" required>
                                <span class="text-danger" asp-validation-for="Name"></span>
                            </div>
                        </div><!-- row -->

                        <div class="row mb-3">
                            <label class="col-sm-4 form-control-label">Year Index: <span class="tx-danger">*</span></label>
                            <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                                <input asp-for="Index" type="number" class="form-control" placeholder="Year Index" required>
                                <span class="text-danger" asp-validation-for="Index"></span>
                            </div>
                        </div><!-- row -->

                        <div class="form-layout-footer mg-t-30 text-center">
                            <input type="submit" value="Add" class="btn btn-info">
                            <a asp-action="Index" asp-controller="Year" class="btn btn-secondary">Back</a>
                        </div><!-- form-layout-footer -->
                    </form>
                </div><!-- form-layout -->
            </div>
        </div><!-- row -->
    </div><!-- br-section-wrapper -->
</div><!-- br-pagebody -->
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        $(document).ready(function () {
            var errorMessage = '@TempData["ErrorMessage"]';
            if (errorMessage) {
                alert(errorMessage);
            }
        });
    </script>
}

GP_MVC/Areas/Manager/Views/Year/Edit.cshtml
@using GP_MVC.Models
@model Year
@{
    ViewData["Title"] = "Edit Year";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}

<div class="br-pagetitle">
    <h3 class="text-info mr-3">Edit Year</h3>
</div><!-- d-flex -->

<div class="br-pagebody">
    <div class="br-section-wrapper">
        <div class="row">
            <div class="col-xl-12">
                <div class="form-layout form-layout-4">
                    <form method="post" asp-action="Edit" asp-controller="Year" asp-route-returnurl="@ViewData["ReturnUrl"]">
                        <input type="hidden" asp-for="Id" />
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="row mb-3">
                            <label class="col-sm-4 form-control-label">Year Name: <span class="tx-danger">*</span></label>
                            <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                                <input asp-for="Name" type="text" class="form-control" placeholder="Year Name" required>
                                <span class="text-danger" asp-validation-for="Name"></span>
                            </div>
                        </div><!-- row -->

                        <div class="row mb-3">
                            <label class="col-sm-4 form-control-label">Year Index: <span class="tx-danger">*</span></label>
                            <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                                <input asp-for="Index" type="number" class="form-control" placeholder="Year Index" required>
                                <span class="text-danger" asp-validation-for="Index"></span>
                            </div>
                        </div><!-- row -->

                        <div class="form-layout-footer mg-t-30 text-center">
                            <input type="submit" value="Save" class="btn btn-info">
                            <a asp-action="Index" asp-controller="Year" class="btn btn-secondary">Back</a>
                        </div><!-- form-layout-footer -->
                    </form>
                </div><!-- form-layout -->
            </div>
        </div><!-- row -->
    </div><!-- br-section-wrapper -->
</div><!-- br-pagebody -->
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        $(document).ready(function () {
            var errorMessage = '@TempData["ErrorMessage"]';
            if (errorMessage) {
                alert(errorMessage);
            }
        });
    </script>
}

GP_MVC/Areas/Manager/Views/Year/EditMaterial.cshtml
@model GP_MVC.Models.Material
@{
    ViewData["Title"] = "Edit Material";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}

<div class="br-pagetitle">
    <h3 class="text-info mr-3">Edit Material</h3>
</div>

<div class="br-pagebody">
    <div class="br-section-wrapper">
        <div class="row">
            <div class="col-xl-12">
                <div class="form-layout form-layout-4">
                    <form method="post" asp-action="EditMaterial" asp-controller="Year" asp-route-returnurl="@ViewData["ReturnUrl"]">
                        <input type="hidden" asp-for="Id" />
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="row mb-3">
                            <label class="col-sm-4 form-control-label">Material Name: <span class="tx-danger">*</span></label>
                            <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                                <input asp-for="Name" type="text" class="form-control" placeholder="Material Name" required>
                                <span class="text-danger" asp-validation-for="Name"></span>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-sm-4 form-control-label">Material Grade: <span class="tx-danger">*</span></label>
                            <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                                <input asp-for="M_grade" type="number" class="form-control" placeholder="Material Grade" required>
                                <span class="text-danger" asp-validation-for="M_grade"></span>
                            </div>
                        </div>

                        <div class="form-layout-footer mg-t-30 text-center">
                            <input type="submit" value="Save" class="btn btn-info">
                            <a asp-action="MaterialIndex" asp-controller="Year" asp-route-id="@ViewBag.TermId" class="btn btn-secondary">Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        $(document).ready(function () {
            var errorMessage = '@TempData["ErrorMessage"]';
            if (errorMessage) {
                alert(errorMessage);
            }
        });
    </script>
}

GP_MVC/Areas/Manager/Views/Year/EditTerm.cshtml
@model GP_MVC.Models.Term
@{
    ViewData["Title"] = "Edit Term";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}

<div class="br-pagetitle">
    <h3 class="text-info mr-3">Edit Term</h3>
</div>

<div class="br-pagebody">
    <div class="br-section-wrapper">
        <div class="row">
            <div class="col-xl-12">
                <div class="form-layout form-layout-4">
                    <form method="post" asp-action="EditTerm" asp-controller="Year" asp-route-returnurl="@ViewData["ReturnUrl"]">
                        <input type="hidden" asp-for="Id" />
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="row mb-3">
                            <label class="col-sm-4 form-control-label">Term Name: <span class="tx-danger">*</span></label>
                            <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                                <input asp-for="TermName" type="text" class="form-control" placeholder="Term Name" required>
                                <span class="text-danger" asp-validation-for="TermName"></span>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-sm-4 form-control-label">Term Index: <span class="tx-danger">*</span></label>
                            <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                                <input asp-for="Index" type="number" class="form-control" placeholder="Term Index" required>
                                <span class="text-danger" asp-validation-for="Index"></span>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-sm-4 form-control-label">End Date: <span class="tx-danger">*</span></label>
                            <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                                <input asp-for="EndDate" type="date" class="form-control" required>
                                <span class="text-danger" asp-validation-for="EndDate"></span>
                            </div>
                        </div>

                        <div class="form-layout-footer mg-t-30 text-center">
                            <input type="submit" value="Save" class="btn btn-info">
                            <a asp-action="TermIndex" asp-controller="Year" asp-route-id="@ViewBag.YearId" class="btn btn-secondary">Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        $(document).ready(function () {
            var errorMessage = '@TempData["ErrorMessage"]';
            if (errorMessage) {
                alert(errorMessage);
            }
        });
    </script>
}